#!/bin/sh
#
# script to cleanup snapshot
#
#DISABLE_DELETE=echo
WEEKS=1
SECONDS=$(echo "$WEEKS * 604800" | bc)
WEEKS_AGO=$(echo "$(date +%s)-$SECONDS" | bc)


AWS_PROFILE=XXXXXXXXX
#allow passing in a profile for testing
if [ "$1" != "" ]
then
	AWS_PROFILE="$1"
fi
export AWS_PROFILE

#read -p "Delete images older than $WEEKS weeks from $REPO (y/n)? " CHOICE


#
#R&D to delete only greater than 1 day, need to figure out syntax
#
#IMAGES=$(aws  ecr describe-images --repository-name aro-workflow --output json | jq '.[]' | jq '.[]' | jq "select (.imagePushedAt < $WEEKS_AGO)" | jq -r '.imageTags'|sed 's/\[//g;s/\]//g;s/\"//g'|egrep SNAPSHOT)
#for IMAGE in ${IMAGES[*]}; do
      #echo "Deleting $IMAGE"
##done
#exit 1

n=0
for i in `aws ecr describe-repositories |egrep repositoryName|cut -f2 -d:|sed 's/[\"\,]//g'|sort`
do
	echo "Repo: $i"
	IMAGES=$(aws  ecr describe-images --repository-name $i --output json | jq '.[]' | jq '.[]' | jq "select (.imagePushedAt < $WEEKS_AGO)" | jq -r '.imageTags'|sed 's/\[//g;s/\]//g;s/\"//g'|egrep SNAPSHOT)
	for j in ${IMAGES[*]}; do
		echo "Repo: $i: Image: $j"
	      $DISABLE_DELETE aws ecr batch-delete-image --repository-name $i --image-ids "imageTag=$j"
	done

#        IMAGES=
#        for j in `aws ecr list-images --repository-name $i|egrep SNAPSHOT|cut -f4 -d\"`
#        do

#   aws ecr batch-delete-image --repository-name $i --image-ids "imageTag=$j"

#
#TO DO batching not working
#
		#echo "Image: $j"
#                if [ "$IMAGES" != "" ]
#                then
#                        IMAGES="$IMAGES,imageTag=$j"
#		else
#                        IMAGES="imageTag=$j"
#                fi
#                n=$((n+1))
#
#                if [ $n -ge 99 ]
#                then
#			IMAGES="${IMAGES}]"
#			echo "Deleting $IMAGES"
#                        $DISABLE_DELETE aws ecr batch-delete-image --repository-name $i --image-ids "$IMAGES"
#                        IMAGES=""
#                        n=0
#                fi
#       done

#        if [ "$IMAGES" != "" ]
#        then
#		echo "Deleting $IMAGES"
#                $DISABLE_DELETE aws ecr batch-delete-image --repository-name $i --image-ids "$IMAGES"
#        fi

done
exit 0
`
